all:
	gcc src/test.c src/list.c src/stackADT.c src/test.c -wall -pedantic -std=c99 -Iinclude -o bin/test
	gcc src/maze.c src/list.c src/stackADT.c src/maze.c -wall -pedantic -std=c99 -Iinclude -o bin/test